name: 'Terraform GitHub Actions'
description: 'Runscommands via GitHub Actions.'
author: 'CloudDrove, Inc. Team <hello@clouddrove.com>'
branding:
  icon: 'terminal'
  color: 'grey'
inputs:
  github_token:
    description: 'Github token for cloning.'
    required: true
  tf_actions_subcommand:
    description: 'Terraform subcommand to execute.'
    required: false
  tf_actions_version:
    description: 'Terraform version to install.'
    required: false
  tf_actions_cli_credentials_hostname:
    description: 'Hostname for the cli credentials file.'
    default: 'app.terraform.io'
  tf_actions_cli_credentials_token:
    description: 'Token for the cli credentials file.'
  tf_actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
  tf_actions_working_dir:
    description: 'Terraform working directory.'
    default: '.'
outputs:
  tf_actions_output:
    description: 'The terraform outputs in JSON format.'
  tf_actions_plan_has_changes:
    description: 'Whether or not the terraform plan contained changes.'
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.github_token }} # args for the readme.sh
