# action.yml
name: 'Terraform security scan'
description: 'Scan your terraform code with tfsec'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  modules:
    description: 'Comma-separated list of modules to include'
    required: false
  username:
    description: 'Set user-name'
    required: false
  email:
    description: 'Set Email id'
    required: false
    
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.github-token }} # args for the readme.sh
    - ${{ inputs.modules }}
    - ${{ inputs.username }}
    - ${{ inputs.email }}
